// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOBvCqOSZD_kaUgOrgzLOS0Yatkx1Z6Mc',
    appId: '1:1066764588064:web:4d73b7420e4c680cdf9845',
    messagingSenderId: '1066764588064',
    projectId: 'todo-dd9a7',
    authDomain: 'todo-dd9a7.firebaseapp.com',
    storageBucket: 'todo-dd9a7.firebasestorage.app',
    measurementId: 'G-LJBTBNJTQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv6_ITmm5PbtWrvizveCcttoKPrdJCbzQ',
    appId: '1:1066764588064:android:99ae76df1296b6d9df9845',
    messagingSenderId: '1066764588064',
    projectId: 'todo-dd9a7',
    storageBucket: 'todo-dd9a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU819KpsBdcyb5yTAuCeXzfKCh6QTXjHA',
    appId: '1:1066764588064:ios:2695823315596417df9845',
    messagingSenderId: '1066764588064',
    projectId: 'todo-dd9a7',
    storageBucket: 'todo-dd9a7.firebasestorage.app',
    iosBundleId: 'com.example.todoB1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU819KpsBdcyb5yTAuCeXzfKCh6QTXjHA',
    appId: '1:1066764588064:ios:2695823315596417df9845',
    messagingSenderId: '1066764588064',
    projectId: 'todo-dd9a7',
    storageBucket: 'todo-dd9a7.firebasestorage.app',
    iosBundleId: 'com.example.todoB1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOBvCqOSZD_kaUgOrgzLOS0Yatkx1Z6Mc',
    appId: '1:1066764588064:web:df233b0e3c787b7bdf9845',
    messagingSenderId: '1066764588064',
    projectId: 'todo-dd9a7',
    authDomain: 'todo-dd9a7.firebaseapp.com',
    storageBucket: 'todo-dd9a7.firebasestorage.app',
    measurementId: 'G-E69WGG4N73',
  );

}